# Generated by Django 4.2.27 on 2026-01-01 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stocks",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="OptionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("underlying_price", models.FloatField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("contracts_data", models.JSONField(default=list)),
                ("expiration_dates", models.JSONField(default=list)),
                ("strike_range", models.JSONField(default=dict)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_snapshots",
                        to="options.stock",
                    ),
                ),
            ],
            options={
                "db_table": "option_snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OptionContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("strike", models.FloatField(db_index=True)),
                ("expiration", models.CharField(db_index=True, max_length=8)),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CALL", "Call"), ("PUT", "Put")], max_length=4
                    ),
                ),
                ("bid", models.FloatField()),
                ("ask", models.FloatField()),
                ("last", models.FloatField(blank=True, null=True)),
                ("mid_price", models.FloatField(blank=True, null=True)),
                ("volume", models.IntegerField(default=0)),
                ("open_interest", models.IntegerField(default=0)),
                ("implied_volatility", models.FloatField(blank=True, null=True)),
                ("delta", models.FloatField(blank=True, null=True)),
                ("gamma", models.FloatField(blank=True, null=True)),
                ("theta", models.FloatField(blank=True, null=True)),
                ("vega", models.FloatField(blank=True, null=True)),
                (
                    "contract_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="options.optionsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "option_contracts",
                "ordering": ["expiration", "strike", "option_type"],
            },
        ),
        migrations.AddIndex(
            model_name="optionsnapshot",
            index=models.Index(
                fields=["symbol", "-timestamp"], name="option_snap_symbol_a48857_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionsnapshot",
            index=models.Index(
                fields=["timestamp"], name="option_snap_timesta_56eab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["symbol", "expiration", "strike"],
                name="option_cont_symbol_f7ee5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="optioncontract",
            index=models.Index(
                fields=["timestamp"], name="option_cont_timesta_7442f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="optioncontract",
            unique_together={
                ("symbol", "strike", "expiration", "option_type", "timestamp")
            },
        ),
    ]
