# Generated by Django 4.2.27 on 2026-01-01 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("sp500_price", models.FloatField(blank=True, null=True)),
                ("vix", models.FloatField(blank=True, null=True)),
                ("market_trend", models.CharField(blank=True, max_length=20)),
                ("volatility_regime", models.CharField(blank=True, max_length=20)),
                ("meta_data", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "market_conditions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="market_cond_timesta_4443fe_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("covered_call", "Covered Call"),
                            ("iron_condor", "Iron Condor"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("entry_cost", models.FloatField()),
                ("max_profit", models.FloatField()),
                ("max_loss", models.FloatField()),
                ("breakeven_points", models.JSONField(default=list)),
                ("profit_profile", models.JSONField(default=list)),
                ("delta", models.FloatField(blank=True, null=True)),
                ("gamma", models.FloatField(blank=True, null=True)),
                ("theta", models.FloatField(blank=True, null=True)),
                ("vega", models.FloatField(blank=True, null=True)),
                ("probability_of_profit", models.FloatField(blank=True, null=True)),
                ("risk_reward_ratio", models.FloatField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="options.stock",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "strategy_type", "-timestamp"],
                        name="strategy_hi_symbol_0eb017_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="strategy_hi_timesta_f0ad8e_idx"
                    ),
                ],
            },
        ),
    ]
