# Generated by Django 4.2.27 on 2026-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(db_index=True, max_length=50)),
                (
                    "symbol",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("records_collected", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "collection_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_type", "status", "-created_at"],
                        name="collection__job_typ_4ebf81_idx",
                    )
                ],
            },
        ),
    ]
