#!/bin/bash
# Combine all app-specific schema files into a single file
# This creates schema_all.sql which can be used for database setup

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/schema_all.sql"

echo "=========================================="
echo "Combining Schema Files"
echo "=========================================="
echo ""

# Start with master schema file (includes TimescaleDB extension)
echo "📄 Reading master schema.sql..."
cat > "$OUTPUT_FILE" << 'EOF'
-- ============================================================================
-- BIFROST TRADER OPTION - COMPLETE DATABASE SCHEMA
-- ============================================================================
-- 
-- This file is auto-generated by combine_schemas.sh
-- It combines all app-specific schema files into a single file.
-- 
-- ⚠️  IMPORTANT: Django models are the SINGLE SOURCE OF TRUTH
-- 
-- Schema organization matches Django app structure:
--   - Options app: stocks, option_snapshots, option_contracts
--   - Strategies app: strategy_history, market_conditions
--   - Data collection app: collection_jobs
-- 
-- Last Updated: 2026-01-01
-- PostgreSQL Version: 17
-- TimescaleDB Version: 2.x
-- 
-- ============================================================================

-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

EOF

# Append each app-specific schema file
echo "📄 Appending schema_options.sql..."
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "-- OPTIONS APP SCHEMA" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/schema_options.sql" >> "$OUTPUT_FILE"

echo "📄 Appending schema_strategies.sql..."
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "-- STRATEGIES APP SCHEMA" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/schema_strategies.sql" >> "$OUTPUT_FILE"

echo "📄 Appending schema_data_collection.sql..."
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "-- DATA COLLECTION APP SCHEMA" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/schema_data_collection.sql" >> "$OUTPUT_FILE"

# Add TimescaleDB hypertable setup
echo "📄 Adding TimescaleDB hypertable setup..."
cat >> "$OUTPUT_FILE" << 'EOF'

-- ============================================================================
-- TIMESCALEDB HYPERTABLE SETUP
-- ============================================================================
-- Run this after creating the option_snapshots table
-- SELECT create_hypertable('option_snapshots', 'timestamp', if_not_exists => TRUE);

-- ============================================================================
-- SCHEMA VERSION TRACKING
-- ============================================================================
-- Version 1.0.0 (2026-01-01)
--   - Initial schema creation
--   - All core tables: stocks, option_snapshots, option_contracts, 
--     strategy_history, market_conditions, collection_jobs
--   - TimescaleDB hypertable setup for option_snapshots
-- 
-- Future changes should be documented here with:
--   - Version number
--   - Date
--   - Description of changes
--   - Migration notes if needed
-- ============================================================================
EOF

FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
echo ""
echo "✅ Schema files combined successfully!"
echo "   Output: $OUTPUT_FILE"
echo "   Size: $FILE_SIZE"
echo ""

# Copy to docs/database/ for documentation
DOCS_DIR="$SCRIPT_DIR/../../docs/database"
DOCS_FILE="$DOCS_DIR/schema_all.sql"

if [ -d "$DOCS_DIR" ]; then
    echo "📄 Copying to docs/database/ for documentation..."
    cp "$OUTPUT_FILE" "$DOCS_FILE"
    echo "   ✅ Copied to: $DOCS_FILE"
    echo ""
else
    echo "⚠️  Warning: docs/database/ directory not found, skipping documentation copy"
    echo "   Expected: $DOCS_DIR"
    echo ""
fi

echo "📝 Usage:"
echo "   psql -U bifrost -d options_db -f $OUTPUT_FILE"
echo ""
echo "📚 Documentation:"
echo "   Schema also available at: docs/database/schema_all.sql"
echo ""

