#!/bin/bash
# Refresh database schema files
# Combines app-specific schema files and generates markdown documentation
# This script:
#   1. Combines schema_*.sql files into schema_all.sql
#   2. Generates markdown documentation (SCHEMA.md) for MkDocs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/schema_all.sql"
DOCS_FILE="$PROJECT_ROOT/docs/database/SCHEMA.md"

echo "=========================================="
echo "Refreshing Database Schema"
echo "=========================================="
echo ""

# Step 1: Combine schema files
echo "📦 Step 1: Combining schema files..."
echo ""

# Start with header (includes TimescaleDB extension)
echo "📄 Creating schema_all.sql..."
cat > "$OUTPUT_FILE" << 'EOF'
-- ============================================================================
-- BIFROST TRADER OPTION - COMPLETE DATABASE SCHEMA
-- ============================================================================
-- 
-- This file is auto-generated by refresh_schema.sh
-- It combines all app-specific schema files into a single file.
-- 
-- ⚠️  IMPORTANT: Django models are the SINGLE SOURCE OF TRUTH
-- 
-- Schema organization matches Django app structure:
--   - Options app: stocks, option_snapshots, option_contracts
--   - Strategies app: strategy_history, market_conditions
--   - Data collection app: collection_jobs
-- 
-- Last Updated: 2026-01-01
-- PostgreSQL Version: 17
-- TimescaleDB Version: 2.x
-- 
-- ============================================================================

-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

EOF

# Append each app-specific schema file
echo "📄 Appending schema_options.sql..."
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "-- OPTIONS APP SCHEMA" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/schema_options.sql" >> "$OUTPUT_FILE"

echo "📄 Appending schema_strategies.sql..."
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "-- STRATEGIES APP SCHEMA" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/schema_strategies.sql" >> "$OUTPUT_FILE"

echo "📄 Appending schema_data_collection.sql..."
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "-- DATA COLLECTION APP SCHEMA" >> "$OUTPUT_FILE"
echo "-- ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/schema_data_collection.sql" >> "$OUTPUT_FILE"

# Add TimescaleDB hypertable setup
echo "📄 Adding TimescaleDB hypertable setup..."
cat >> "$OUTPUT_FILE" << 'EOF'

-- ============================================================================
-- TIMESCALEDB HYPERTABLE SETUP
-- ============================================================================
-- Run this after creating the option_snapshots table
-- SELECT create_hypertable('option_snapshots', 'timestamp', if_not_exists => TRUE);

-- ============================================================================
-- SCHEMA VERSION TRACKING
-- ============================================================================
-- Version 1.0.0 (2026-01-01)
--   - Initial schema creation
--   - All core tables: stocks, option_snapshots, option_contracts, 
--     strategy_history, market_conditions, collection_jobs
--   - TimescaleDB hypertable setup for option_snapshots
-- 
-- Future changes should be documented here with:
--   - Version number
--   - Date
--   - Description of changes
--   - Migration notes if needed
-- ============================================================================
EOF

FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
echo ""
echo "✅ Schema files combined successfully!"
echo "   Output: $OUTPUT_FILE"
echo "   Size: $FILE_SIZE"
echo ""

# Step 2: Generate markdown documentation
echo "📝 Step 2: Generating markdown documentation..."
echo ""

# Run Python script to generate markdown (it will also verify schema)
python3 "$SCRIPT_DIR/refresh_schema.py"

echo ""
echo "=========================================="
echo "✅ Schema Refresh Complete"
echo "=========================================="
echo ""
echo "📁 Generated files:"
echo "   ✅ scripts/database/schema_all.sql (for deployment)"
echo "   ✅ docs/database/SCHEMA.md (for MkDocs documentation)"
echo ""
echo "📝 Usage:"
echo "   psql -U bifrost -d options_db -f $OUTPUT_FILE"
echo ""
echo "📚 View in MkDocs:"
echo "   mkdocs serve"
echo "   Then navigate to: Database > SCHEMA"
echo ""


